# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Log and raise an exception (stop) from C++
#'
#' A message is logged at level ERROR, then stop(message) is called.
#' An optional additional message (details) can be given,
#' to be logged at level DEBUG.
#'
#' @inheritParams log_n_stop
#' @family log and stop from R or C++
#'
#' @examples
#' \dontrun{
#'   tryCatch(log_n_stop_C("essai de log_n_top_C", "via tryCatch()"),
#'            error= function(e){log_info(paste("erreur :",e))},
#'            finally=function(e){log_info(paste("finally :",e))})
#' }
#' @keywords internal
log_n_stop_C <- function(message, m_details) {
    invisible(.Call(`_posir_log_n_stop_C`, message, m_details))
}

#' Computation of a batch of trajectories of the 1D POSIR process
#'
#' Implements the functional \eqn{G_\delta(\cdot)}
#' from paper \insertCite{BaBoNe24}{posir}.
#' Takes a matrix whose lines are from simulated white noise trajectories
#' and computes from it the trajectories of the associated 1D POSIR process.
#'
#' @param Z matrix whose lines are simulated white noise trajectories.
#' @param Intdgrid decreasing vector of the integers \eqn{1\le k\le Ndis}
#' such that \eqn{k/Ndis} is in the grid for \eqn{\delta},
#' where Ndis is the rows number of Z.
#' Generally obtained as Ndis*deltagrid,
#' where the vector deltagrid is the desired grid for \eqn{\delta}.
#' (Beware: no checking is done in this internal function.)
#' @inheritParams n_traj_simu
#' @inheritParams simulationDir
#' @inheritParams check_grid
#' @seealso [run_simu()], [batch_filename()]
#' @family POSIR process generators
#'
#' @return A matrix with n lines and length(Intdgrid) columns.
#'
#' @references
#'   \insertAllCited{}
#' @keywords internal
n_traj_simu_1D_C <- function(Z, Intdgrid, is_standard) {
    .Call(`_posir_n_traj_simu_1D_C`, Z, Intdgrid, is_standard)
}

#' Computation one trajectory of the 2D POSIR process
#'
#' Implements the 2D version of the functional \eqn{G_\delta(\cdot)}
#' from paper \insertCite{BaBoNe24}{posir}.
#' Takes a square matrix containing a simulated white noise 2D-sheet,
#' and computes from it one trajectory of the associated 2D POSIR process.
#'
#' @param Z square matrix containing a simulated white noise 2D-sheet.
#' @inheritParams n_traj_simu_1D_C
#' @inheritParams n_traj_simu
#' @inheritParams simulationDir
#' @inheritParams check_grid
#' @seealso [run_simu()], [batch_filename()]
#' @family POSIR process generators
#'
#' @return A vector with length(Intdgrid) elements.
#'
#' @references
#'   \insertAllCited{}
#' @keywords internal
n_traj_simu_2D_C <- function(Z, Intdgrid, is_standard) {
    .Call(`_posir_n_traj_simu_2D_C`, Z, Intdgrid, is_standard)
}

