# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Log and raise an exception (stop) from C++
#'
#' A message is logged at level ERROR, then stop(message) is called.
#' An optional additional message (details) can be given,
#' to be logged at level DEBUG.
#'
#' @inheritParams log_n_stop
#' @family log and stop from R or C++
#'
#' @examples
#' \dontrun{
#'   tryCatch(log_n_stop_C("essai de log_n_top_C", "via tryCatch()"),
#'            error= function(e){log_info(paste("erreur :",e))},
#'            finally=function(e){log_info(paste("finally :",e))})
#' }
#' @keywords internal
log_n_stop_C <- function(message, m_details) {
    invisible(.Call(`_posir_log_n_stop_C`, message, m_details))
}

#' Random generation using Rcpp if possible, else a call to R
#'
#' Random generation according to a distribution.
#' Calls the [Rcpp][Rcpp::Rcpp-package] function if rDisName is among the list
#' {"rnorm", "runif", "rlnorm", "rCenterdPareto"},
#' else calls the R Function with name rDisName.
#'
#' @param n number of generated i.i.d. random variables.
#' @param rDisName name (string) of the distribution function.
#'
#' @return A pseudo-random vector of length n.
#' @export
#'
#' @examples
#' random_C_or_R(10,"rnorm")
#' myrdistrib=stats::rnorm
#' random_C_or_R(10,"myrdistrib")
random_C_or_R <- function(n, rDisName) {
    .Call(`_posir_random_C_or_R`, n, rDisName)
}

#' Random simulation of trajectories of the 1D or 2D POSIR process
#'
#' Simulate n trajectories (as \eqn{\delta} decreases)
#' of the (discretized) 1D or 2D POSIR process.
#'
#' @param Intdgrid decreasing vector of the integers \eqn{1\le k\le Ndis}
#' such that \eqn{k/Ndis} is in the grid for \eqn{\delta}.
#' Generally obtained as Ndis*deltagrid,
#' where the vector dgrid is the desired grid for \eqn{\delta}.
#' (Beware: no checking is done in this internal function.)
#' @inheritParams random_C_or_R
#' @inheritParams n_traj_simu
#' @inheritParams simulationDir
#' @inheritParams check_grid
#' @seealso [run_simu()], [batch_filename()]
#' @family POSIR process generators.
#'
#' @return A matrix with n lines and length(grille) columns.
#' @keywords internal
n_traj_simu_C <- function(n, Ndis, Intdgrid, rDisName, is_standard, d) {
    .Call(`_posir_n_traj_simu_C`, n, Ndis, Intdgrid, rDisName, is_standard, d)
}

